= Temporary Environment Variables

:caution-caption: :fire:
:status:
:url-repo: https://github.com/guenhter/temp_env_vars


ifdef::status[]
image:https://img.shields.io/crates/l/serial_test.svg[MIT license,link={url-repo}/blob/main/LICENSE]
image:{url-repo}/workflows/CI/badge.svg[Build Status (GitHub Actions),link={url-repo}/actions]
endif::[]

`temp_env_vars` allows to to manipulate enviornment variables during a test and reset all changes when the test is done.

[CAUTION]
====
The software currently in the starting phase and will change
====

== Installation


[CAUTION]
====
This crate is not yet available via crates.io (comming soon)
====

```toml
temp_env_vars = { git = "https://github.com/guenhter/temp_env_vars.git", branch = "main" }
temp_env_vars_core = { git = "https://github.com/guenhter/temp_env_vars.git", branch = "main" }
```


== Usage

`temp_env_vars` can be used in two different forms:

. as macro `#[temp_env_vars]`
. with `TestEnvScope::new()`


=== Use as macro

`#[temp_env_vars]` is the preferred way to use the `temp_env_vars` crate.
Every change to envionrment variables within the execution of the test function
will be reset after the test has ended.

If more tests are used with this macro, those tests will be executed sequentially to avoid an enviornment variable mixup.

```rust
#[test]
#[temp_env_vars]
fn test_some() {
    std::env::set_var("FOO", "BAR");
    assert_eq!(std::env::var("FOO").unwrap(), "BAR");

    // Env vars get reset when test is done
}
```


=== Use with TestEnvScope

If resetting the environment variables after the test execution is not sufficient, but the reset must happen somewhere within the test, the `TestEnvScope` can be used to have better control.

Whenever the created `TestEnvScope` goes out of scope, all env vars are reset.

```rust
#[test]
#[serial] // Advices to use serial, alse parallel tests could mix up envs
fn test_some() {
    let _env_scope = TestEnvScope::new();
    std::env::set_var("FOO", "BAR");
    assert_eq!(std::env::var("FOO").unwrap(), "BAR");

    // After "_env_scope" goes out of scope, all vars are restored
}

#[test]
#[serial] // Advices to use serial, alse parallel tests could mix up envs
fn test_bar() {
    let _env_scope = TestEnvScope::new();
    std::env::set_var("FOO", "BAR");
    assert_eq!(std::env::var("FOO").unwrap(), "BAR");

    drop(_env_scope); // After "_env_scope" goes out of scope, all vars are restored


    // "FOO" is not longer set here.
}
```


== Contribution

Contribution are always welcome in any form.

You acknowledge and agree that the owner reserve the right to change the license of the Work, including but not limited to all Contributions previously submitted by You, at any time without the need for approval from You or any other contributor.

== License

This project is licensed under the https://github.com/guenhter/temp_env_vars/blob/main/LICENSE[MIT license].
